apiVersion: v2
name: cilium single node
description: Cilium Single node k3s Helm chart configured by Ujstor
type: application
version: 1.0.0
appVersion: "1.16.3"

dependencies:
- name: cilium
  version: 1.0.0
  repository: "https://ujstor.github.io/helm-charts-system"
  alias: cilium-k3s

