apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-cilium
  namespace: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: cluster-bootstrap
  source:
    path: helm/system/cilium
    repoURL: https://github.com/Ujstor/k3s-test
    targetRevision: master
    helm:
      version: v3
      releaseName: cilium
  syncPolicy:
    automated:
      selfHeal: true
