apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-ingress-nginx
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook-dependency: system-cilium
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: cluster-bootstrap
  source:
    path: helm/system/ingress-nginx
    repoURL: https://github.com/Ujstor/k3s-test
    targetRevision: master
    helm:
      version: v3
      releaseName: ingress-nginx
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
