apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-cert-manager
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/hook-dependency: system-ingress-nginx
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: cluster-bootstrap
  source:
    path: helm/system/cert-manager
    repoURL: https://github.com/Ujstor/k3s-test
    targetRevision: master
    helm:
      version: v3
      releaseName: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
