apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-external-secrets
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: cluster-bootstrap
  source:
    path: helm/system/external-secrets
    targetRevision: master
    helm:
      version: v3
      releaseName: external-secrets
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
