apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-todo-go-htmx
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  destination:
    namespace: todo-go-htmx
    server: https://kubernetes.default.svc
  project: cluster-bootstrap
  source:
    path: helm/apps/todo-go-htmx
    repoURL: https://github.com/Ujstor/k3s-test
    targetRevision: master
    helm:
      version: v3
      releaseName: todo-go-htmx
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
